Repository AY2425S1-CS2103T-F08-4/tp, pull requests merged in 2024-11, with the labels that each got.

#119 Update UG for sort and find commands
  docs/UserGuide.md
Labels: Documentation

#134 Fix find error message
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: alpha-bug

#136 Change Reminder UI
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderCard.fxml
Labels: type.Enhancement

#143 Add autosort reminders by date
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteReminderCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteReminderCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement

#146 Change app header to NetBook
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#147 Update UG for add command
  docs/UserGuide.md
Labels: Documentation

#152 Add wrap text capabilities
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ReminderCard.fxml
Labels: alpha-bug

#155 Fix link issue in UG
  docs/UserGuide.md
Labels: alpha-bug

#172 Fix Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: alpha-bug

#173 Update DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: Documentation

#185 Update Ui picture and include duplicate person info in UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: Documentation

#252 Add error message for duplicate reminders
  src/main/java/seedu/address/logic/commands/AddReminderCommand.java
  src/test/java/seedu/address/logic/commands/AddReminderCommandTest.java
Labels: type.Bug

#267 Fix date bug
  src/main/java/seedu/address/logic/parser/AddReminderCommandParser.java
  src/main/java/seedu/address/model/person/LastSeen.java
  src/main/java/seedu/address/model/person/Reminder.java
  src/test/java/seedu/address/logic/parser/AddReminderCommandParserTest.java
  src/test/java/seedu/address/model/person/LastSeenTest.java
Labels: type.Bug
